<html>
  <head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title><%= U::htmlize(pageTemplate["title"]) %></title>
    <link rel="stylesheet" href="/css/styles.css" type="text/css"/>
    <link rel="icon" href="/images/favicon.ico">
    <script type="text/javascript" src="/jquery/jquery-1.8.3.min.js"></script>
  </head>
  <body lang="en">
    <header>
      <div class="headercontainer">
        <div class="header">  
		  <h1><%= U::htmlize(pageTemplate["title"]) %></h1>
        </div>
      </div>
    </header>
    <div class="contentcontainer">
      <div class="content">
